### Homework 3 Numpy Arrays and Pandas

1. Open `cars.csv` in jupyter and look at the data. (Double click `cars.csv` to open in a new tab).
2. We are converting each **column** into a numpy array.
3. Notice we have text, integer and float data. 
4. Take care not to overwrite your starter code.

In [3]:
#Starter code. Do NOT modify this cell
import pandas as pd
import numpy as np

# Read in dataset
df = pd.read_csv('cars.csv',delimiter=';')

# Convert each column to an np.array
car = df.Car.to_numpy()
mpg = df.MPG.to_numpy()
cylinders = df.Cylinders.to_numpy()
displacement = df.Displacement.to_numpy()
horsepower = df.Horsepower.to_numpy()
weight = df.Weight.to_numpy()
acceleration = df.Acceleration.to_numpy()
model = df.Model.to_numpy()
origin = df.Origin.to_numpy()

# create an array of headers
headers = np.array(['Car', 'MPG', 'Cylinders', 'Displacement', 'Horsepower', 'Weight','Acceleration', 'Model', 'Origin'])

1. (2 pts) What are the numpy datatypes for the `car`,`mpg`, `horsepower` and `origin` arrays? (Hint: Not `type(car)` and use `print()` to print the numpy type.)

In [4]:
print("cars", car.dtype)
print("mpg", mpg.dtype)
print("horsepower", horsepower.dtype)
print("origin", origin.dtype)

cars object
mpg float64
horsepower float64
origin object


2. (1 pt) `numpy` is often imported as `np`. What is this action called? Why might you do this? 

In [5]:
# numpy is often imported as np becuase it is simple and help easily reconize numpy. we do this because it makes reading the code easier

3. (2 pts) Each of the arrays (cars, mpg, cylinders, etc..) has how many dimensions? Show how to find this using code. 

In [6]:
print(car.ndim)
print(mpg.ndim)
print(cylinders.ndim)
print(displacement.ndim)
print(horsepower.ndim)
print(weight.ndim)
print(acceleration.ndim)
print(model.ndim)
print(origin.ndim)

1
1
1
1
1
1
1
1
1


4. (3 pts) What is the ___ of `horsepower`?
- sum
- min
- max
- median
- Optional: mode (May need to google help) (1 pt extra credit)

In [14]:
print(np.sum(horsepower)) 
print(np.max(horsepower))
print(np.min(horsepower))
print(np.median(horsepower))

import scipy
from scipy import stats as st
print(st.mode(horsepower))

42033.0
230.0
0.0
93.5
ModeResult(mode=np.float64(150.0), count=np.int64(22))


5. (2 pts) Select the last element in each subarray (do this with one operation.)

In [8]:

select_more = np.array([[1,2,3],
                      [4,5,6],
                      [7,8,9]])
# returns array([3, 6, 9])
last_elements = select_more[:, -1]
print(last_elements)

[3 6 9]


6. (2 pts) Use the built-in `np.lookfor()` function to search for `'log'`.

Use the function you find and apply it to `mpg`.

In [11]:
#np.lookfor(log)
# no longer exsits

7. (2 pts) Use boolean indexing to create an array of `True/False` using `origin` and the value 'US'.

In [10]:
boolean_origin = origin == 'US'
# df['US']
boolean_origin

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True, False,  True,  True,  True, False, False, False,
       False, False, False,  True,  True,  True,  True,  True, False,
        True, False,  True, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True, False, False, False, False, False, False,
        True, False,  True, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True, False, False, False, False,  True, False, False,
        True, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True,  True,  True,  True,  True, False,  True,
       False, False,  True,  True, False,  True,  True, False, False,
       False, False,

8. (2 pts) Apply your index (from above) to the `car` array. You should now only see cars that are of US origin. 

In [17]:
us_cars = car[boolean_origin]
#boolean_origin = 
print(us_cars)

['Chevrolet Chevelle Malibu' 'Buick Skylark 320' 'Plymouth Satellite'
 'AMC Rebel SST' 'Ford Torino' 'Ford Galaxie 500' 'Chevrolet Impala'
 'Plymouth Fury iii' 'Pontiac Catalina' 'AMC Ambassador DPL'
 'Chevrolet Chevelle Concours (sw)' 'Ford Torino (sw)'
 'Plymouth Satellite (sw)' 'AMC Rebel SST (sw)' 'Dodge Challenger SE'
 "Plymouth 'Cuda 340" 'Ford Mustang Boss 302' 'Chevrolet Monte Carlo'
 'Buick Estate Wagon (sw)' 'Plymouth Duster' 'AMC Hornet' 'Ford Maverick'
 'AMC Gremlin' 'Ford F250' 'Chevy C20' 'Dodge D200' 'Hi 1200D'
 'Chevrolet Vega 2300' 'Ford Pinto' 'AMC Gremlin'
 'Plymouth Satellite Custom' 'Chevrolet Chevelle Malibu' 'Ford Torino 500'
 'AMC Matador' 'Chevrolet Impala' 'Pontiac Catalina Brougham'
 'Ford Galaxie 500' 'Plymouth Fury iii' 'Dodge Monaco (sw)'
 'Ford Country Squire (sw)' 'Pontiac Safari (sw)'
 'AMC Hornet Sportabout (sw)' 'Chevrolet Vega (sw)' 'Pontiac Firebird'
 'Ford Mustang' 'Mercury Capri 2000' 'Plymouth Cricket'
 'Dodge Colt Hardtop' 'Chevrolet Vega' 'Ford

### Use numpy or pandas to answer the following questions.

9. (3 pts) What is the average horsepower for `Europe` cars? (Hint: create a boolean index of 'US' apply it to horsepower and perform the calculation.)

In [18]:
boolean_origin = origin == 'Europe'
e_cars = horsepower[boolean_origin]
print(e_cars)
e_cars.mean()

[115.  46.  87.  90.  95. 113.  48.  90.  70.  76.  60.  54. 112.  76.
  87.  69.  46.  90.  49.  75.  91. 112. 110.  83.  67.  78.  75.  75.
  67.  71.  70.  95.  88.  98. 115.  86.  81.  83.  70.  71. 102.  88.
 120.  58.  78.  78. 110.  48. 103. 125. 115. 133.  71.  71.  77.  71.
  69.  76.  78.  48.  48.  67.  67.   0.  62.  88.  74.   0.  80. 110.
  76.  74.  52.]


np.float64(78.78082191780823)

10. (3 pts) On average are Japanese cars more fuel-efficient than US cars? Show the code that you used to determine this.  

In [18]:
boolean_origin = origin == 'US'
us_cars = mpg[boolean_origin]
uscars_mpg = us_cars.mean()
print(uscars_mpg)

19.688188976377955


In [22]:
boolean_origin = origin == 'Japan'
j_cars = mpg[boolean_origin]
japancars_mpg = j_cars.mean()
print(japancars_mpg)

if(japancars_mpg > uscars_mpg):
    print("japanese cars are more efficent")
else:
    print("us cars are more efficient")

30.450632911392404
japanese cars are more efficent


11. (3 pts) What is the correlation coefficient of `mpg` and `weight`? What is a correlation coefficient? What does the result indicate about the relationship between mpg and weight? 

In [23]:
correlation_coefficient = np.corrcoef(mpg, weight)
print(correlation_coefficient)

[[ 1.         -0.78750994]
 [-0.78750994  1.        ]]


Extra credit: (3 pts) Create a new pandas dataframe that has the average mpg, weight, and horsepower per country of origin

In [24]:
df.head()

Car   MPG  Cylinders  Displacement  Horsepower  \
0  Chevrolet Chevelle Malibu  18.0          8         307.0       130.0   
1          Buick Skylark 320  15.0          8         350.0       165.0   
2         Plymouth Satellite  18.0          8         318.0       150.0   
3              AMC Rebel SST  16.0          8         304.0       150.0   
4                Ford Torino  17.0          8         302.0       140.0   

   Weight  Acceleration  Model Origin  
0  3504.0          12.0     70     US  
1  3693.0          11.5     70     US  
2  3436.0          11.0     70     US  
3  3433.0          12.0     70     US  
4  3449.0          10.5     70     US

In [29]:
new_df = df.groupby('Origin').agg({'MPG':'mean', 'Weight':'mean', 'Horsepower':'mean'}).reset_index()

In [30]:
new_df.head()

Origin        MPG       Weight  Horsepower
0  Europe  26.745205  2431.493151   78.780822
1   Japan  30.450633  2221.227848   79.835443
2      US  19.688189  3372.700787  118.011811